### ISSUE TITLE
Supports only logr? what about uber/go-zap?

### ISSUE THREAD

**Issue by hyorigo** [LeKovr/webtail#10]
```go
// Service holds WebTail service
type Service struct {
	cfg *Config
	hub *Hub
	wg  *sync.WaitGroup
	log logr.Logger
}
```

**Comment by LeKovr** [comment]
logr is an "abstract interface" for logging. As written in [logr README](https://github.com/go-logr/logr/blob/master/README.md):
> There are implementations for the following logging libraries:
...
go.uber.org/zap: zapr

webtail cmd uses go-zap exactly, see [setup.go](https://github.com/LeKovr/webtail/blob/f44a14c43b91fcdfc35381b71b13be94b36be47f/cmd/webtail/setup.go#L51)
