### ISSUE TITLE
Any middleware for Gin?

### ISSUE THREAD

**Issue by hyorigo** [LeKovr/webtail#11]

**Comment by LeKovr** [comment]
No. Webtail Service has [ServeHTTP method](https://github.com/LeKovr/webtail/blob/master/webtail.go#L64), so "middleware for Gin" might be written like [Gin sample](https://github.com/gin-gonic/gin/issues/51#issuecomment-48201747).

Meanwhile it would be nice to add an example for webtail usage within gin

**Comment by LeKovr** [comment]
== No coments for 4+ months. Closing discussion ==
