### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by xorguy** [LeKovr/webtail#15]
Hi.

If possible, and is not a problem of resources, and due to the release of 64 bits of Raspbian for some Raspberry Pi it will be great to add ARM64 build of webtail.

I tried to build from your code adding GOARCH=arm64 and it built, but did not test because I have not installed, yet, the x64 bits for my Pi4, will do in the following days.

Thanks in advance.

Regards.

**Comment by LeKovr** [comment]
I've added build for linux/arm64 in [v0.46.3](https://github.com/LeKovr/webtail/releases/tag/v0.46.3) but docker image needs some work yet

**Comment by xorguy** [comment]
Thanks!

**Comment by LeKovr** [comment]
Docker problem was solved in  [v0.46.6](https://github.com/LeKovr/webtail/releases/tag/v0.46.6). All done

**Comment by xorguy** [comment]
Tried to pull and run container in ARM64 with latest version and it is working flawlessly.

Thanks a lot!
