### ISSUE TITLE
Does this automatically refresh the new content? 

### ISSUE THREAD

**Issue by ccdos** [LeKovr/webtail#16]
I've run the program with docker, but I need to refresh the page with F5 every time to see the new logs.

**Comment by LeKovr** [comment]
Yes, it does. Page automatically updated via websockets when file content is changed

**Comment by LeKovr** [comment]
@ccdos , look for errors at browser's js console please

**Comment by ccdos** [comment]
Originally I deployed it on windows 11. I just deployed it again on ubuntu 18.04 and it works fine. It works perfectly for my needs. Thanks for your work!
