### ISSUE TITLE
error: New tail error: stat log/: no such file or directory% 

### ISSUE THREAD

**Issue by aogg** [LeKovr/webtail#18]
docker logs -f webtail
[  info ] 2024/10/14 13:18:55 main.go:40: webtail v0.34. WebTail, tail logfiles via web
[  info ] 2024/10/14 13:18:55 main.go:41: Copyright (C) 2016-2017, Alexey Kovrizhkin <lekovr+webtail@gmail.com>
error: New tail error: stat log/: no such file or directory%     

```
 docker rm -f webtail;\
> docker run -d --restart=always --network common-all --name webtail --privileged \
> lekovr/webtail

```

**Comment by LeKovr** [comment]
Webtail shows external logs. Try to mount dir with them.
See [sample](https://github.com/LeKovr/webtail/blob/master/docker-compose.yml#L12C8-L12C24)
