### ISSUE TITLE
How To add multiple Log file root paths? 

### ISSUE THREAD

**Issue by reddysainathn** [LeKovr/webtail#3]
Hello,

This app is really useful, can you please help me How to view multiple directories, so I can have one port to open for multiple application Log files.

-Thanks.

**Comment by LeKovr** [comment]
Multiple roots support will require the following changes:
1. [config](../blob/master/tailer/tailer.go#L18): change `--root` option from `string` to `[]string` with items like `alias:root` and appropriate parse it [here](../blob/master/tailer/tailer.go#L48)
2. [indexer](../blob/master/tailer/tailer.go#L221): to walk through all roots and add `alias:` as channel name prefix
3. [tailer](../blob/master/tailer/tailer.go#L100): to change `channel -> filename` translation

Also it might require some updates of [index page](../blob/master/html/webtail.js#L59)

So, we could prefer adding support of journald for multiple log sources
